name: deploy-auth

on:
  push:
    branches:
       - main
    paths:
       - 'auth/**' 
       
jobs:
  build:  
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t bilalkhawajaa/auth .
      - run: docker login -u  $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push bilalkhawajaa/auth   
       - uses: digitalocean/actions-doctl@v2   
         with:
            token:  ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-1-24-4-do-0-sfo3-1666259905479
      - run: kubectl rollout restart deployment auth-depl       
              
