name: deploy-manifests

on:
  push:
    branches:
       - main
    paths:
       - 'infra/**' 
       
jobs:
  build:  
    runs-on: ubuntu-latest
    steps: 
       
       - uses: digitalocean/actions-doctl@v2   
         with:
            token:  ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
       - run: doctl kubernetes cluster kubeconfig save k8s-1-24-4-do-0-sfo3-1666259905479
       - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
